const TESTIMONI_LAMA = [
  { inisial: 'HI', nama: 'Hafizul I.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjuTk2rEHEb3545fcKAbigxz2LpInaJkBeOdAd93ihY8XniZRAKfa8Nwp-yrlkoKJCjlAL_KbHIH6MaM_f74MDX59faEPOO3zSVq4b0g70PehEkDuDnEXxTkuCDykoLnzebXby4aG6TxRJZEy0LbN0NPYprAfwv8JWrCkEYPvDeShKc73NDL8GDiUZk31U/s320/IMG_5134.jpeg', teks: 'terbaik inimah,fast respon,bisa chat kapanpun,hasilnya juga sangat memuaskan,sangat membantu dan berjasa dalam hidup saya' },
  { inisial: 'B', nama: 'B***', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Respon cepat sekali, pembelajaran yang diberikanpun mudah dimengerti, dan hasil olahdata juga sangat rapi dan mantappppppppp ✨️ 💥' },
  { inisial: 'EN', nama: 'Eka N.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjkL0k_X5cqALD8I1mNL8wvyp2sC93ufD3WZWrDOJ_ot-JceGxceybvrhuu8dN53lW0f7LuZWUWIRisU7h1qrOAcLBiEiolHOJDEuxmsUrqbIvuSNagsWOCYkyQrySwjxhs1AxAy0-OQoqi3lglPMETkZu0NmlmpUds8N7V0fFm4RH-uTSbN0u2X-YZ1WU/s320/D4274861-9BB2-46DC-85EE-287A70E74AEE.jpeg', teks: 'The best banget masya Allah sesuai target hasil sangat memuaskan dan sangat terbantu banget cita cita wisuda tepat waktu terlaksana 🥰' },
  { inisial: 'FF', nama: 'Fanny D. F.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEinfn1Va9sLXRQWuu2_8QICi407q3a1z89j5uIgfYrLKpuJL6VDxycT7UxpRho1sP7uXp4sbvBinck92d8jMEGVSjNFNSfOXe4htbJrV9rNXnBPv_NTSOXsE0WNkqYJURz72_UcyQ0o-1c8dy2AgchpX2QrRWfI5v8NuVWb16gQRZfXn4kZIKLbO7NH9-o/s320/19BEA9B2-6027-4B65-9F95-F9553FD149FF.jpeg', teks: 'pelayananya sangat baik, adminnya fast respon dan baik sekalii, cara pembelajarannya juga sangat bagus dan menyenangkan, makasii banyak!' },
  { inisial: 'WA', nama: 'Winda A.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhM9aj1M8qA4jOe_-ky_LC_0UdEz75mn5aDtYGiBAd4o8ebgvkC4btkItY3cSkBIN_MuW2uNLL_SQUcYboPZXmAvpx-5XseT34BYSBAwe1xoXogcEHW5iRY1efOFurH0YAPuJY90JZtvSAXKEhAtlfCdvMGiBqVAWaMXZDIAZIP_gge89JMKGmDIjbeLr0/s320/IMG_2047.jpeg', teks: 'Saya sangat puas dengan layanan olah data yang diberikan. Profesionalisme dan ketepatan waktu mereka sangat mengesankan.' },
  { inisial: 'FF', nama: 'Fidia F.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEht_qrFoOABGvA3Y5FxG1VW98FhCZUY89_4f3EPtAvulKoDQkYSZXCDu6P94A5HCx-IF11l8j7MJ2cJ5KjRy3bPLJUgAA3ahgO6TazpIA-kgWpdVJsnv38LIn71zcmEdkLV4CUYaEA5UBc_PeawSF8w0vk8-dxjtZwlweCicoxll2pY5BX4gaWcATXLnls/s320/IMG_8622.jpeg', teks: 'Mengatasi masalah tanpa masalah the best pokonya meringankan beban hidup saya menjaga mental saya 👍🏻' },
  { inisial: 'DS', nama: 'Disti S. P.', subtitle: 'BAB I–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgrQM4ixU64TX65TYiGtSFFcPBrB07vjicBIyt6OIvXNYNRsQgI7oOjHnqlHGJwzlXQxq-JgmIxPTskfEJGQ21fAqkdcMuaCr7LxTaH8Rm6LN-0vZgaGkirKSh-B8Mo3q1b-9ExPbrO2dtdnjEeF7rn89RGzdbsEQ38QEoc0_2IGonWA_tbVJphKRSFzyU/s320/Disti%20sabrina%20putri.JPG', teks: 'Masyaallah sangat sangat puas, kakanya super ramah dan bimbingan super detail dan teliti serta pengerjaannya juga sangat bagus dan rapih, pokonya 10 bintang' },
  { inisial: 'SP', nama: 'Salma P. L.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgAsK6Jhly-OZNClim_exxJWinVy-AOZAS8-Ozb5ycOLdRd1yNtADlsLCYsdRVnGGcF2Huaf4BP2FgC4izjws0dnrpfL3847pd3U_krBkss5SSRqkleSqxvNoFnJR6rNY1jXyMgqnxRFVJUB_9bptX6z4qYo3-M_swVwNOlTjEj2CkjlUU-qAEMV4Fs4BQ/s320/salma.jpeg', teks: 'responnya sangat baik bisa menjelaskan dan membantu sampai dengan paham, mengolah data dengan benar dan tepat. terimakasih banyak sukses selalu!' },
  { inisial: 'RK', nama: 'Ranti K. G.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhwLmjPBubA_8EfzOALjHJUg67p8x-Prad5lMbROnu9O3ukAkvUlEHDWIu612ip-oqmM1F-zDYw-M3rzMgo34VKyX59SSK_WbBYSBAwe1xoXogcEHW5iRY1efOFurH0YAPuJY90JZtvSAXKEhAtlfCdvMGiBqVAWaMXZDIAZIP_gge89JMKGmDIjbeLr0/s320/rianti.jpeg', teks: 'wow sangat bgs, pengerjaan cepat penjelasan bagus tepat dan membantu tidak membalas cht lama sll fast respon tidak jutek ramah dan baik 👍🏻' },
  { inisial: 'WM', nama: 'Widy M.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgaDMVszjRDNcGKxHn0ONWq85qut8CuQMk-gnam7ufejCgzZ3f9fgXRrTAQNwmfJv0y3IbydIbuFK9q0ob90jzyrd8b_66bN-vom62ONTiiCOcKmXGPDJ9DIk_UNJXbJUROw-IupjqTddm1lIRKI_GOatk50GthMRSi9I_13efbGV_Zt-Ep_9IEJQI8GkE/s320/widy.jpeg', teks: 'Sangat jelas dan penjelasan yang dijelaskan lebih rinci sehingga mudah di pahami boleh bertanya berkali-kali jika tidak ada yang di mengerti sangat ramah dan fast respon' },
  { inisial: 'GR', nama: 'Gery R.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjV8a1hS4VXq31hfLh4WAEiVIJuLbKmLQjyw2PSETnEJJmMHLtKk3HdyndUtpJVpEEryYXOCli7CIseX9mWsHc1g4fRR2DsBo4qyX4r6Qxs1UWdSInX-7H4oPhnbQ-jAr4OA-hEIHeYONXF8CnY5vcNzgHxjMF_jh95Ccw6EVP4DhzV6dQQQ8Rfvce5_Og/s320/Gery%20Raflyansyah.jpeg', teks: 'Sudah sangat baik menurut saya, Sangat fast respon dan ramah, materi yang di berikan cukup jelas, Sangat baik dalam membimbing.' },
  { inisial: 'LA', nama: 'Lydia A.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Pakai jasa olah data di Amkobar sangat fast respon dan hasil olah data nya sesuai dan dijelasin sampai paham. Terima kasih Amkobar 🙏🏻' },
  { inisial: 'RA', nama: 'Rifdah A.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi4jrpacQ4zKSANdu2EHirm549qo7NGsbwgpyWBdTLewZLMiuEwb_sQP9bMpN4Im_jtuQhtmRmhrD5repoh8K3qSsTg7xWqlA-ltxCHb3J-vowChsZ10NteXwmSPBGncUPHvzW6K7-SuxTMwSb51IgCBvgi0_JmHawlQ8sSvNA8HVyNW9JxpcErMIN7mic/s320/Rifdah%20Agnia.jpeg', teks: 'suka banget sama hasil kerjanya!! kakak nya pun baik bangett selalu ngasih arahan sampai benar-benar paham, fast respon dan selalu selesai tepat waktu' },
  { inisial: 'AC', nama: 'Adityani C. P.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiKYKpf5aDSYgERGn-Qm8aAjUcMqI6L3JfDqCqE4abdEnnW-N-R7-gnJvsBPyv7aHEhyphenhyphenXayGv3J5DpjnTuSRt-HdzAwr1M3mYnr3lE8C0aGDl_eknDIACAiovUuLHarxRvLt7p40RME90s74zrIH79lRA_bf3sdqk8QW_-WWgzzidFbhh82JaROlQ3HxOQ/s320/Adityani%20Cahya%20Putri.jpeg', teks: 'sangat membantuu sekali bagi aku yang super lemot hehehe, mana ngejelasinnya superr detail bangett sampe yang gak paham jadi paham 🤩👍' },
  { inisial: 'RD', nama: 'Rizky D. F.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'jos lengkap bahan dan sistem nya siap 24 jam! penjelasan jelas dan pengerjaan sangat cepat memuasakan, terimakasih🙏 sukses buat amkobar' },
  { inisial: 'LN', nama: 'Lina N. H.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjW1qF2ncR_fBc-FleCNgi9vtkgRPdYi-6KKVNKZSduVMDc7MKu0_MvnTO_5pq9HiguXEHfvSF7_ozLI8upS_oZ1zbLQKWP19AvhraEjjWZFxcu8FtPcqtScj6SSOSlaJxFV7d879OIJ7Hd2y2qLMH63A6Cllb3XSxOJ_Kx6auBcg_YN44RGuy1E3Y4YIc/s320/lina%20nurul.jpeg', teks: 'Untuk pembelajaran sangatt jelas, dan waktu pembelajaran juga bisa menyesuaikan dengan waktu luang kita. Dijelaskan sampai benar benar mengerti.' },
  { inisial: 'AA', nama: 'Adinda A. N.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi81pAEC8fJxn1xj_qOsrdWMv4nvViOIoo33xiXHueCb-WZauCA5W_4U1fCD8Kbnfw0sNO2rxt76-giaMXAp01z-4DDspXF-rMrnjQWUDIi6o0xVSS0xjb7LjYqra1s-Km84Ye9TAIwKK-zkSJueNmrAXTbtgXzxT1aytBu-SXCpDp8Q9ni3YGViGDmJaI/s320/adinda%20a.jpeg', teks: 'sangat membantu sekali kepuyengaan ini tentang bab 4 bisa teratasi😵‍💫 dijelasin sampe kita bener bener ngerti kalo nanya pun selalu fast respon omagaaaaaa !!!! 🫶🏻' },
  { inisial: 'ZH', nama: 'Zulfah H.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhPavuTRM4Hvbm7Ah1OptEoiMgiJan1B8Po0gmcz5HlO2Z1vklyhVZreVu4OtnpJSk9pbJbum269ER8n1hFkO6eHetkGuU-EPoSpHK4CqFc5gOaBfcTLmheyyKrGhIdLsd3V3x6u16vh9RZBn3KIdB5eAkJ7QtDIpHlkDCFsuwn9_X6kHJQuVcShf1mJxY/s320/zulfah%20H.jpeg', teks: 'Terbaik banget pokonya, pas belajar juga ngejelasin nya jelas terus mudah dipahami, kita nanya terus juga ga ngambek🫶🏻 fast respon! pokonya ngebantu banget 🤩💐' },
  { inisial: 'SS', nama: 'Sarifah S.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEinummXd1toQtoaFzG3MCkQz3wAt4KVDuw3LMzYpASsoxrAi6QzL5DnlS-fvFyUhaqHi_CC6Cwdj5m3rjj5pUxQP9kgfPeqgLDSb9v2SskrnYOmjAIe0rXXyXNZ_koNx72qeqvVetH2iYpCVvC7j_WBW86yTe1fxLVPdukRRCQJSyu_3E8qYu0tH5F3Mss/s320/sarifah%20s.jpeg', teks: 'yang paling penting untuk penjelasannya mudah di mengerti dan di pahami, untuk hal yang tidak di pahami bisa dengan bebas di tanyakan. terimakasih 🙏' },
  { inisial: 'MP', nama: 'Muhammad P.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi-dsT12dtL4icIgQY2G0-eqldAcH7g5bDUMVBLyEAoDGNWNf4vVrMloiiEdF4wzDdV_6RjSGxd0CV6rige2n2n_xktTaT9YPyeb8gnTI_ocP2DlWyL0NWigs2J2lQgtFNb1JVdAwT6SBx0Ri79HQW2yl4tRRB67pwV3hV_0ApApZr5r3OVLzdxdZ69ZpA/s320/pasyah.jpeg', teks: 'Fast respon, ramah dan jika belum paham bisa minta belajar ulang sampai paham. apapun yang ditanya pasti dijawab. terimakasih sukses selalu' },
  { inisial: 'DN', nama: 'Dita N.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhb0duK9ESnG9FQFg_Lbjc_U7aSMTNU_pHjZv90KRbjqcHjwPg-4tO9HDb3qQrEPXlcEoxHMxGPIqWofnnSasmfTUnPBKQfQPgWv6nCz9S0jUBVe3Zjvmsg2dECFh21g677Lcsx8jF1KNZvlsT2RP3_Jdl-vWrja0UsdwL_xENz_3pn0vXN0Hn3Wsg2sIw/s320/dita%20n.jpeg', teks: 'Terima kasih udah ngebantu banget, adminnya baik banget! Mudah dipahami, responnya bagus, kalo minta tambahan pasti dikasi dijelasin juga.' },
  { inisial: 'SE', nama: 'Salsa E. A.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjXg2xsHuph8x7KZzVnuspu1AjN5mUrS7bYbjh_LVcKE6Rl4JfAY596Da4gEdVwTfQZCN8MHS5CYsdt27iDd7QRWnO3pKM1JmyFbrDZaCrDLIhqhFA_B_eimBNly7Dz1OXlavoRwRSZiW5LaGqDDGVbSrI1c2D5EgMYjw1nBdIAYFlRZ22p08eGXS2fadI/s320/salsa%20e.jpeg', teks: 'puas bgt sama pelayanannya fast respon dan penjelasan diakhir mudah dipahami, pengerjaanya juga detail, rapih. pokoknya puas bgt, RECOMMEDED!!!' },
  { inisial: 'RR', nama: 'Reza R.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhG2DwAJGma-Ptwf1tcUrujERmCNBw0wXBxjkYODe3_1UGge3J8S_0aersS9OEh0JKOwxDcTTjOXLhB7YdLDbqpAYsjwh6kAfXku72-m8Gv5e3QKl0xKcDUm9rAyVEGUnqDrgamAraaeDjT-dVoo37fJV1gIMY4StD5nqt0XR79kRo/s320/Reza%20R.jpeg', teks: 'makasiii banyak kaa sudah banyak bantu bangett, adminnya baik bangett, responnya bagus cepet, pas belajar mudah dipahami. makasiii banyak kakak kakak 💗' },
  { inisial: 'ZA', nama: 'Zahra A. F.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhfY24UUZhATc6zFsg4QkuFlQThyii6gvrOkXVQUgdu9x_zMjsjFwmkkmV6yMve-ikGXGB_IlwsQ-rs-9VSBSL98mn9sKenQwjYogh9qII7sZjunPLe55kj19TWlIF_94ZK7jCAuFXlIq_Du5OSpADpe1xsAJKB4BT5k43wfWRT63lmOXyMwhVkvyA5UV8w/s320/zahrah%20anisa.jpeg', teks: 'makasihh akang udah bantuu, dari awal chat adminnya ramah bangett, pembelajaran barengnga mudah dipahami langsung, selalu ngasih masukan dan saran 🤩' },
  { inisial: 'SY', nama: 'Siska Y. S.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEimapH41DkA1yz4dqKyETnIVgJbgpru39NtalVAyb-n2UGb9gyCYlMI_vjbcK7-3gDbv4OpArcyd-Evl1OjthB__zMtHa-Z8NDhJ1YnyeId8xgZOp862Bpr9tRSAcRpxrF1GW9jd9iN1oyauqkLskTHTaxTi-dsIKWXj3iG_ObNDuOhq1U-5HJ6QU1F7K8/s320/siska.jpeg', teks: 'Sangat membantuu, pengerjaan terbilang lumayan cepat, Belajarnya juga dapat dipahami, dibimbing sampe bisa. Kalau ada pertanyaan admin fast respon!!' },
  { inisial: 'N', nama: 'Nabila', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'baik, sabar menghadapi otak yang kadang lemot atau ngefreeze wkwk, fast respon, sesi pembelajaran yang baik, pelayanan yang baik, hasil yang baik' },
  { inisial: 'FT', nama: 'Fajar T. H. P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEghZPX5ij9gWlvMT2hyNgEi_yN5HjKgHSQYw-OBTKqxyFL4YIUsKCvE8WsdDb7CQo_BXldRLj2Ib2-smGfpwZgJd4rxWtXC6TtcVjpkNTu_tQj1Dsd252lKaIu5sFRb4phvgzHcIavCZppIc5BvqgI5DOGB-L-LgZ6Rm1aJtM09GaBa8HcluV02ukAs0Dw/s320/Fajar%20THF.jpeg', teks: 'fast respon, sesi pembelajaran yang baik, pelayanan yang sangat memuaskan' },
  { inisial: 'PD', nama: 'Puteri D. A.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhrklOToOuVnLwTiTowHozy2ZAU4HPPFFnFC9WPX-pPYOkiNt-elyO1D7ar3F9mFyrdzWL10BxZRM-gbUFZysroS1UBztzE8J0rbfFQIJ2if_kQ-qJnmSIYtB7cfIzhOJcAMjNMXCoF5T1kWdizB0a7LznKmP6UGSRgI/s320/Puteri%20D.jpg', teks: 'amanah bgt, olah data nya juga dikerjain cepettt. ga salah olah data disini krn emg amanah. dikasih banyak contohnya, pokonya udah lengkap bgt' },
  { inisial: 'RU', nama: 'Restu U. P.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Hasilnya sangat memuaskan, responnya cepat, mengerjakannya juga sangat cepat, mentornya baik, sopan dan ramah, harga sangat affordable bagi mahasiswa 🙏🏻' },
  { inisial: 'S', nama: 'Sitinur', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjYyVg3Bq1q8Yqfx_qRiEJ6Sb_OOW3OSn4GXuHPPWFgo6idrvMrGXYkNbiUtx1Q_cIVmT9fNqYXLIoymussH1NJiHDGaT1codP1zl9Oi2ZL834zGqfM5C7NmeGSg8rjtxAGFyu73CIxct25aodzxKhaKtrw3XCyipmQVMlTzhi93lL3ui-HqCMt_LUT3b4/s320/sitinur.png', teks: 'Fast respon on wa, bisa di hubungin kapanpun, Pengerjaan olah data dan deskripsinya detail, rapih dan sesuai. Makasi kang andi' },
  { inisial: 'IA', nama: 'Insira A. H.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'sudah cukup baik dalam melakukan pengerjaan hasil olah data dan dalam melakukan sesi belajar atau penjelasan yang diberikan dapat dengan mudah dipahami' },
  { inisial: 'RI', nama: 'Robi I.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjBCx4ITbP6LIwTPeX9yaoUYe-0OGlr212rCRwOIzMvAWh9sRsNSj__h61fDsISyYYZGNuIWc6mQ5OXWz5r3RWRg2tCchPnwOt7VTV5TbgpySjzu2_lxSXanKn0hBh1ToZmNsWzX11pOwZYrVQyhMO-2X_E-1HBXWRNkNGDc3a_Wpcm5hm_qXmwFCbj0FU/s320/Robi%20Irfan.jpeg', teks: 'Terimakasih banyak sudah membantu saya dalam mengerjakan tugas akhir' },
  { inisial: 'MA', nama: 'Muftin A. M.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Penjelasannya sudah jelas dan sangat membantu, pelayanannya pun sudah baik, pokoknya mah sudah mantap semua lah, ramah dari segi pelayanan, sukses terus!' },
  { inisial: 'HS', nama: 'Hilda S.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5MhqkZl0SVwcbiB46CQViVZEqAnvryUMA0WXB-aodi2B1aoBYxfHtqLN-nMkD1wHwttjJQ51w9OxfKxYhvp4zNSSjRcCszZ1_fab45bBW7pirx2n8xJowAg383Ebl39nRf_NDSqbWabt9M_58ykzUpF6fMUTYKkjqMjY4JUqLTquKexCc_2yKOSU/s320/Hilda%20Sicylias.jpg', teks: 'Kakaknya ramah dan fast respon banget, pengerjaan juga cepet, hasilnya dijelasin sampai bener-bener paham. Makasih, sukses selalu!!' },
  { inisial: 'RS', nama: 'Rahma S. N.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgCSzvM1a1ujMYkuPJgYVAW7g5WSPBMugA8LG6fj8pGGmx-ZjwQGWW0FAr0oSdox1OgbVNfU9THxp3yfdCUzVgI34znk8ZjYPQu_Q5CzXLLu98IcJPfnUxwUbHjKc4Oz5sQ3oSxhozTEX8c1ukwLmkbGRveM-tICxXyuV6uz5BtwxnEo3J0PWXylxxCsfDk/s320/Rahma%20Syaripatun%20Napsah.JPG', teks: 'Terimakasih banyakk.. sudah sangat berjasa dan membantu aku dalam pengerjaan skripsi ini. Benar-benar sangat di bantu selain dalam proses pengerjaan juga dibantu dalam proses pemahamannya ✨' },
  { inisial: 'R', nama: 'Resha', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Terimakasih buat kakakkk, udah ngajarin sampaii bisaaa, ngerespon selalu cepettt, selalu welcome kalau di tanya-tanya. sukses selalu buat kakakk!!!' },
  { inisial: 'RN', nama: 'Ratu N.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Respon tim sangat cepat pembelajaran sangat menyenangkan dan tidak boring, hasil olahdata valid semua sidangpun jadi lancar bagus keren' },
  { inisial: 'NW', nama: 'Noviyani W.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'cepet responnya dan akang nya sangat baikk, sangat sangat sangat banyak sekali membantu dan juga banyak ilmu yg di dapat. terima kasih banyakkk 🙏🏻' },
  { inisial: 'MI', nama: 'Muhamad I.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhAd5kWIFvVzatl4vgR6767_XNAZwp0TtyBIHvypMMUd_hzen89JrJfFwpo7n9hn6_Sg2brcp2Eu4fCmN4LsaMIaHSWBU73x92wyb9sMHDuZ-0210nrsuTAJrRHE37mYsm0a7KoyYieAodR2Zgjnd2t3eFcZFpQXPZhpUhtZudbzm0KAhNOmX27f8DgXGY/s320/Muhamad%20Ikbal.jpg', teks: 'Fast respon dalam membalas chat dan Diajarin sampai paham dengan pembawaan yang santai jadi klean ga perlu merasa sungkan dan tegang 🤙' },
  { inisial: 'Y', nama: 'Yola', subtitle: 'BAB IV', rating: 4, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Mengajar nya sudah baik sampai benar-benar mengerti materi, belajar nya juga tidak hanya sekali tapi sampai 2 Kali. Hasil output nya sudah bagus.' },
  { inisial: 'C', nama: 'Cantika', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhsKMM4iLslZaBvX6JUIb9ZkBYAjc18i3hyphenhyphen9a45tsWelELUyXOWbGqcQfVJPua08VKh_mNCsUKqrYBYwx7LCmlsgRBGISmLhz09ClITVDUMzIRvfdFmMg9W1y6x7N8itBgCoIbwIoyHDNJhGb9NB_Zc-pfAKZrkAQ6wlCnrCLuU8l_2mtvtFlrGcActQQI/s320/Cantika.jpeg', teks: 'ngebantu bgt dlm mengolah data spss, penjelasan yang dikasi juga dikasi tauu sampe kita paham👍🏼 fast respon, ramah, sabar.. terima kasih yaa sangat terbantuu👌🏼' },
  { inisial: 'RM', nama: 'Ritia M.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiKZWD2rgKMVpNRiShGKKIDqa0MUHI2GNUZFAsB5aV8VY5a8toTamghLbJb4jQ6QoCFkLx_NHkOkhbJ7Bsnar-fPYRQ2dLLEU-BOO-gn7eSZDJOEoptuD226jskT_AJ9KpodvKwkw5SD2Qs31KMlv9hNWvm6Yfy7o/s320/Ritia%20Mulyasa.jpeg', teks: 'fast respon, sabar dalam menjelaskannya meskipun nanya berkali kali, ngebantu bgt dalam olah data tugas akhir ada garansinya jugaa worth it pokoknyaaa!' },
  { inisial: 'W', nama: 'Wina', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjIDy6b8eqYX4qgnKaFvkHW5EQWft5wwsRiNEMfS86kKz4pZ9cpz1tPDLuUXSzxVVG2RsEz7NsBVonBaQB0Wxc3XrNcrblw3d2_wRAW8PIkDu1NhTeSgnpx6gn5TYod2rOoXJHrrx-JOEoptuD226jskT_AJ9KpodvKwkw5SD2Qs31KMlv9hNWvm6Yfy7o/s320/wina.jpeg', teks: 'Pelyananan bagus, cara mengajar juga asik dan mudah dimengerti. makasih bnyak ya kang sehat dan berkah selalu, Jangan berhenti jadi orang baik' },
  { inisial: 'F', nama: 'Faridah', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjoHJ12NrOYunapqQxN6njAPOZkcFqckHShpaALpUdYbUeDjswghulWshqq3xdfD2doPQOMhnuRQ5UuSRbLpkkGISOPLVtOqSt3WrDXU3FeTUhosEQIuIL1gJizZHk4cpbGlD6TLpjJ-P1wc6H9NPDsCxle0c4SmgJbaq1NpW9YnZZRWGcDdWNTPAB4xN4/s320/faridah.jpg', teks: 'dalam pembelajaran sangat mudah dimengerti, respon akangnya sangat cepat, baik, seru juga selalu menjawab jika kita tidak mengerti. terima kasih banyak akangg' },
  { inisial: 'MA', nama: 'M Alfi M.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjEIrxTAdLRn_x8k5lpnKF7T8O1wjt6nqCBEaIhaw84gPyCivQtcJrUYHDwBoGTC9qo-9ebMhPmSq-Ey6cz1H_iFpyAuCvJfiFJY0S0D0uEgfvI3KS4QFGzyUxUsTSbgbAz6mXUHsKOIXfQSelHoCVa1fRe1Fm7ek8BJCiHbS_ITNbBoCxcN52cXFhtn6w/s320/M%20ALFI%20MUNAWAR.jpg', teks: 'Proses pengerjaannya cepet, bimbingan belajarnya juga santai dan nyaman. Hasil olah datanya lumayan lengkap, responnya juga cepat dan ramah. Makasih banyak 👌👍🏼' },
  { inisial: 'D', nama: 'Dini', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgh4zWwgLu6DmVqnaJ3NWdSsogBwz5v8QwvcaEFiMYtjeJMXgAq8mQ1l59aOi9R3XHnLD8krqbpUKmDj2N8vwYc_zB54ClNVc3h8WY3KLsAcvsbR8RZ2RQwERAt6l7Vv-u7NrwcKPll-ffsAldXyUPjCJPELJeZWDoLhgbpfEBRS_sDaryenFs-UsYrwQc/s320/dini.jpg', teks: 'Terimakasih banyak atas jasanya sangat membantu sekali dengan pelayanan yang ramah, respon cepat, pembelajaran diberikan pemahaman yang sangat mudah dimengerti' },
  { inisial: 'SF', nama: 'Shinta F.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjlxiem_dXcRtygRMggz3-C8JGG6mBt5iHDkVdsri7Vhfep1Wu7DVK9q8qrqikGzsuPMV0Eg9WjfIDgKU6UjyQ2E_5GfzMh9SKW1XvYDOXIry_OhCrZyAEvXLG-PbrrPbGrEQlMo5Fs7c63h4J7qpvh6HZNA5Cxz5C7gsd9vrKZnm3CHt3oTa-0JmGaens/s320/shinta%20fitriyani.jpeg', teks: 'Terimakasihh telah membantu pembuatan skripsi ini. Responnya cepet bangett, penjelasannya bagus, ada revisian langsung dikerjain. Pokoknyaa oke bangett good joob!' },
  { inisial: 'WD', nama: 'Wahyu D.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDIZuqULSK-YOSMqAMqbkYeO9a3ooBF5cOB045kLiEsNj0YD_kYXw3uq7ucVNolIFUYcl9bL5rko2YbnYsVRTQd6Wcloj8E6VELTqmfzatZGmP-ECVTzWPKBpoCGthcpS9i_4F9R_4LqhZ7LBn3EuQPRKLnb_MTjzsIWjIb7A6j14xsizpA4N6eD6YByo/s320/foto%20Testimoni%20amkobar.png', teks: 'Cukup baik dalam memberikan pelayan dan cepat tanggap dalam merespons pertanyaan, memberikan pembelajaran sehingga kita menjadi lebih paham' },
  { inisial: 'RS', nama: 'Ridwan S.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjdmOljpWxjEXyhaHNLdM8ZmeKxE7V_M9aEEnEPbqHO7s27xeM8v5EgoBR_0uPs73e-h9E4uUdXpYbbLSeFq-4y-wfUXFjuxwKqL6OyY3jc7_3LTflWDmkAsfANz59w3qygK46O9OOruyX9cyproDmXKKI1l-ypOr4QWmRYY9bjZYBuQtRkxzV5t9_7VYo/s320/Ridwan%20Septian.jpeg', teks: 'Olah data spss di amkobar sangat memuaskan, dari segi pelayanan admin sangat ramah dan asik terutama kang andi, dari segi waktu pengerjaan sangat baik sukses terus!' },
  { inisial: 'R', nama: 'Regina', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjUiMRLFv9DG_anHSdW6CVPrGGA4MBYrvGmBUrEdlc9e3nM8Vs1W9bqsXBKVFhu-unknm1brFCGukMvd1COXGXDKTaBLw_jR1sN_uwkhe5ayayPFeD9ySts5FkrEaC3SNbSg8JBrg47MMF9uk95vwgWvzAVsMeTgPZ-xyfYRti199nCYADav5lQQJEmb84/s320/regina.jpeg', teks: 'memuaskan sekali uhuy, harus coba disini guys, worth it banget, amanah lagi, wajib coba ya ges, pkonya the best deh, trimss' },
  { inisial: 'AN', nama: 'Andi N. A.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhrQyk66wTCgrHY5DiMUJc-KRdQo_MXWh0dJWGECsv2ViYEE9q6SM9uwGK71z7Z7oSRUa_0pqLf1Jl04mfHGFqqZxh0PAFlnobNMEv0Fc1-KadwywqHYkjJHKqr4KQrELC6UBiTtpwmHaNoRQ4aW8piIZAGRetx46g9MGrckhbWA4qugU2tGpcNhBLVjko/s320/andi%20nur.jpeg', teks: 'Terimakasih sudah membantu saya wisuda. Aman amanah gercep pokonya mantappppp Pembelajaran mudah di mengerti, bisa di hubungi kapan pun dan dimanapun' },
  { inisial: 'AF', nama: 'Achmad F. F.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhJ3VRD7zDu8a9nv9ibwCA_0PXDU_Rud0KBqQAmfDvGmcwa82nXQE0JVDBe-B0wubQXqFzqIQLRKEpdLEF3ZzNbemvGt9l0zHURkQNLEDY9Nhb5D7GcPYSz1o4S5Rdb5CVpWfPRja2UkAe7w9xdo-QQFxuT7OmkJ928m8-9bj8RnTIWcZVIEJ2jJnWw8gM/s320/Achmad%20Faizal%20F.jpeg', teks: 'Terimakasih yaa buat akang, karna telah sangat membantu dalam pengerjaan skripsi ini. Semoga semakin sukses dan lancar. Aamin, terimakasih banyak kang' },
  { inisial: 'OL', nama: 'Oki L. S.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEicZAD1w3Pvma9r6zJG15L8hev_1p8TtZdij-blmxXuyRe3PsJoEPGNsr6jeLDP-cHYqWr0v02FMXsETQlTOokQ4jw7pHq5Gc94KS0MGJmvbdGGGdVHjY1emkXLriCtdPvmThQy7f-X00M6AIlMCDFLQgbMUQ3-etKSyFEf8dw-KAEDrdlggFj1gPe1Weo/s320/Oki%20lukman%20setiaki.jpeg', teks: 'Respon baik, hasil olah data gampang dimengerti, revisi mudah, pembelajaran mudah di ikuti, mudah diajak komunikasi, arahan mudah dipahami, terjangkau' },
  { inisial: 'DB', nama: 'Dinda B.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhoATwmkRIEJOJwbT03snFFp2Z2vfzCKkjMWULtjTW84xJqe4JFguZbI12iqux97tDxtnfJ_eP7a0mM4p-uXYU3FSqBnSljXXEJHtrLQzIMuG0wYMJECKfMLRI_NUotgWo0BaZa-YRLGyiRrB-C2wfTxhQY6o54Zcd-bw0hRSAtjTH9PR8rTvMDhvbzxHg/s320/Dinda%20Bidara.jpg', teks: 'kecepatan dan merespon pertanyaannya sangat baik sekali, penilaian dan pengerjaan hasil olahdatanya pun bagus dan valid. Cara penyampaian materi membuat kami mengerti.' },
  { inisial: 'T', nama: 'Tasya', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhQGGGrXKGF-EGenGn1rXE-l0Tqdx3RNjU8zMfgMM98mG1g3bMcHT4FUI5ShPxOECDqu7ov05mzYWzQWw7kNKZMrS9fclMOvy9SUE6Oe_qZeVtMRdOLMFJrtBjVnHpR3TulI3iS1XdpeOL_SBPfWSENdD60tPbYEp6WCLoLPlMVLGPvvl_Jv8lYd1npTcc/s320/Tasya.jpeg', teks: 'makasi banget buat amkobar yang ngebantu aku banget dalam pengerjaan skripsi ini, dari yang awalnya clueless tentang perdataan sampai paham. makasi banyak amkobar sukses selalu' },
  { inisial: 'JN', nama: 'Jenni N. F.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjqLLMhvHDSD-Olo4_DqSk1oWHMj_bWJiC4hndIGN13HleNGYjn0YOkoNzpZRwbxCywUyRGWYyLh1zOAx5Z8ua9tU2B7ejrwdtJjiU_5XEqXuIOpG3_WrTREmmNu-AldC8A6murnp1fauk_79eqOfhX9JOJaYpEM_U8r7-FIMj9yUgyOHF-uIMKlclKpaQ/s320/jenni%20nur%20fauziah.jpeg', teks: 'untuk hasil olahdata nya udah sesuai sama panduan dari kampus, sangat membantu sekali' },
  { inisial: 'H', nama: 'Hanna', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgNjl0UGdDmnuDICmJekvEiT2SqzowSWoIFUY9J4rF-lNd7vt6HfLRYUq_LvuC-69HbKEeJj8V2BUy8cLaZGyJ2jvCEQCwQUu_W4XIEQ2cfrXv7T8iWGXD0VXWMtUEn8l_4eNqMzpiXWlYbm-3gIHnBXJ5CsBetRKkkYO8X78288ECS8z0MEQfC14ehmUE/s320/hanna.jpg', teks: 'keren banget, ramah banget, respon baik dan cepat juga data aman sentosa, pokoknya kalo pusing skripsi ini solusinya. cara mengajarnya juga asik jadi sangat mudah dimengerti.' },
  { inisial: 'RF', nama: 'Rizal F.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg0JAkPrxsyzgrjW8W_D6lZ82tQARvTrp5r-H_pza99up-mvOU_lO_zKwdujIqVfiXIafiYLuOhUMUUzinD1bI7liK9M-KTKTz79eXjSNULotft1p6ZFLCTiaeA5TbYO9wlVC7azIiLM7ocmu07xpPLSRdGNs2Y4X5sUOWkT0Ju-o0wS9-_tVJczxfV/s320/rizal%20f.jpg', teks: 'Sangat membantu dalam mengolah data spss ga cuma itu kalian juga diberikan penjelasan sampai paham dan di akhir juga ada revisi juga🤙' },
  { inisial: 'DQ', nama: 'Daffa Q.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgQTGB5AvzJh4prB30JerJxhjJRPgFUoWvgKQJXE6EC2KugFiEZjWmrm00um4czEghPT11SPFljro4T1XQLQqqi4uoBv2F0c04se4-mmXg-2IZff2IPwt1hk4W7TtXj9LLx7tipEC00__xmoOb5tsGqNoMEXVXnbv5nOMvQj5HlhzyNHvpHMCfjirXN/s320/dafa.jpg', teks: 'mudah dimengerti, fast respon, yg penting garansinya Well pisan' },
  { inisial: 'SR', nama: 'Sandra R. D.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhfCFMju_Uq0-GWvEKlSzUcxc0DnL5_qn9zgPUdjdcqEyfLPu6QmiRYpE-hRwydc8A-eH6TyfSgifznvBDIxiJhLOuGeYdne3Y2d4bvZ3kn3EddGUNsEnVUprUAKPNM8-ToJK8RVzmXQ9_Lqyl-5QK7tKliHL7t7VsPGbFx-TmKIl_TF8moLacE92sc/s320/sandra.jpg', teks: 'Pengerjaannya sangat detail, penyampaiannya juga sangat baik' },
  { inisial: 'RR', nama: 'Rytainda R. N.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhKYGN8ViOnEW9nmKzOPS7gVzho2m62VEXLg7F6fHOoaO9WqQoQg5_um4_8FDwHpgc8Weoq1HJnE4AdlHmrKOUN3forY_tzC2mZ87V5j5vjva6HL0j9qCU2g7WT9iefvPvKvYP5zXdOBvbx45yJue--mNuYBFIj7M1f0Hzg9lQSfbJcr-ih-gA7jps2/s320/ryta.jpg', teks: 'Sangat Baik Dalam Segi Penjelasan, dan Sangat Puas Dalam Pemaparan Materi nya, Kalau ada yg mau ditanyaim juga langsung respon, mantap👍' },
  { inisial: 'MI', nama: 'Muhammad I. A.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgVosWYmEgT6uRhwLiMrVgC_mvq5wVnEtO9tOKIce2jLBfHgp6a0G-ALY-82D4PJ8xjg-SP0n1lCbyZuvdw9i3PGiz5OxGPi5UvFodLqoH7g8MAZoQtaF-2hLz_fHXQL777BBmqCLKSSoDaNGxZwzZIkT9mykbduZrMZWFYgQN-tulSLRXdTFop8rBj/s320/ilham%20a.jpg', teks: 'Baik untuk dalam membantu revisian, cepat dalam mengerjakan skripsi. dan mudah dipahami untuk pembelajaran' },
  { inisial: 'M', nama: 'Mayang', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5EGkG77QbffbVHIeOm1gnVdU2c79BJFR-qFmNqq7oY7Llo64MvZiT9R4NhsrNTNnZhJDgRD4GOV4LGfP8HkyGNQ-OauwsjHXrtj3wqTxeb21DX7yxS1QbTPvfkFT4DvVepqBVHYnxZRMxKq_iDEribZc7vwbDBSXfDTE3RMDo23vFJZUtH4UBLRGl/s320/mayang.jpg', teks: 'Sangat sangat memuaskan. Pengerjaan skripsinya yg detail, rapih dan tepat jadi ga perlu bolak balik revisi. Kapanpun di hubungin pasti langsung di respond, di ajarin sampe ngerti!' },
  { inisial: 'AN', nama: 'Asmi N. H.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgqe-gqnfhheseMsgJdOMOaQ6CuSW4CXHt6HW4IPiuJut8r073uDGypbSqhcAXdkIppPWe74opsKk6cK4CroKndACfaP7edfkhWrwjdCjJq7-icb22YVg24KRP_sIiWONKWElEa4XDRMbDR114Lwaqq6WGAz2oIEMKCFaV6yp7K3E2J2IJfN0CLBN_b/s320/Asmi%20Nurul%20Husna.jpg', teks: 'Sangat mudah dimengertii, kalo ada yang mau ditanyain langsung direspon👍🏻👍🏻' },
  { inisial: 'WD', nama: 'Windyah D. P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhlzEsihkS1GzsC6vOab_vmf29fzrDd3Zdx0D1lC0BssmqI_uLfcCffLGQ8oQ5X3-sxupbUfVy7AqmPcPQcYkCwoGCs9_SRZntLUVivqP7VYMvgHwA5dFI4QMGFFeDGcqi0LdbSZtQs5qR97Yhr5w0tL8TPG6jkF8Qpr2LMbSwV581ipl6n66aOfqNq/s320/windya.jpg', teks: 'Sangat baik dalam menjelaskan, dan mudah dimengerti, pengerjaannya juga cepat' },
  { inisial: 'AY', nama: 'Agus Y.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjCTNcaKB3bW9lXVidKzlSmI2Gx_PX3ZCIs_t545y4xgGMxqwTpuYPPzJn6gA1ybJgho43vp27M14N5hZDhQvPJeDxu8Q1keU4BrXd2EJnQ4e2oU-epuNQDF1am0UnlgrQlGBQoQoepHnNLRfWSE5hHUFSHiUMVLoWVjyfkCIeTCGZ5tWGOOsTJSGRU/s320/Agus%20Y.jpg', teks: 'Benar-benar sangat memuaskan, dari mulai pengerjaan, dan hasil nya pun sangat memuaskan, ditambah waktu dalam pengerjaan sangat sebentar dan benar membantu saya.' },
  { inisial: 'DR', nama: 'Dea R. A.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjO2NVAbL4iZ9E8jy9YK1a6PbPCZ1hkihz00mlASQLBvacMj4cvL5r1tGbfIdTg-TSwTOH3zKvAsmOIRLsNcrcGroyQAtTmSmGoklGjprFW-IKPxxRfPGRinmEGtI1suj4Cxwn46e1xNxsRHZd_uRnX3F4oufTJI-rX3-Vd2R2uTtK14dTHcN_6DN8j/s320/Dea%20RA.jpg', teks: 'sangattt asikk, seru, memuaskan sekali yyy. belajar berkali kali langsung lego' },
  { inisial: 'HK', nama: 'Hegar K.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgZCk18fsMSXhbA71yBV-R-MfyflfErCyKOwGGa1vXrIpTBV4yYYDCGywAf2ze3s5GUEd9OszUrUoevs0uBz_xKL527v8gw1LUoDNAtRoolF98-T0_ZdGVdbL1Ht8Ngk1T6pVeah-aL5D86HbdwCC41T2XuHIY0F69yPAGtpldELWv1g20FSBnSf8Mv/s320/Hegar%20K.jpg', teks: 'Sangat baik dalam segi penjelasan materi dan pelayanan, sangat puas dalam pemaparan materi yg di jelaskan' },
  { inisial: 'Y', nama: 'Yulianto', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0td5w3vf49eXQOVscOLPT7Em8W3Eig_ttH87Lu3KLVWPtI2Cue0BR3jnC0_G7Klp0fFyjW_e--n2Ec0FC1Y7NZvvzIq0vt4-NJ1JzTYDvFgtPKQwYIUznVBzldowdf-KMIDc14bhnoeXuuI-B4vZhqRO5nV3FnFHMKgY6uy1Lnc4i9MmxBn4BxR46/s320/Yuliyanto.jpg', teks: 'Sangat sangat memuaskan Dari Cara penjelasanya cepat dipahami, pelayananya juga sangat baik responnya cepatt 👍' },
  { inisial: 'N', nama: 'Nilam', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjL9RNDdS0YyrQfrs2nnbWwhY015v3IxkDjb8ZxHRZsYMD1ZzrAIyB0jYY8c26NErt7m6CN9HNtgP0wC0QXrA0fPYVOR3aPgtTtkWdHjhAZLAk3MOqq1c5dVScnP2CiKH7WoYlg-GR2J5vqXHfo4YMrk8WnFJuR-vbkUePNK4mLRD-uyzZTT3w9s3DE/s320/Nilam.jpg', teks: 'seru abieezzz, baik bgt lagi tiap butuh selalu ada🌝 jelas banget kalo ngejelasin. tengkyuu semua ilmunya ya semoga dibalas oleh Allah SWT. aamiin' },
  { inisial: 'AA', nama: 'Acep A. K.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjfhktk8T2bRArjGEcgPBBvroOSGba0ipb_j3llJEZIw53iIPVmJV7G0y8BAuf3HhMOr7jBOntRQ2nHRk48WjF0PVJhz-XAQzBoISBc4vbgkKB3C3AnYpE2ShF4qKwskggpYjQDAnL3T0N5_8pEPT60XPTGnQrcHS0uSXs5rpudCzUiaUPhAst5LPnW/s320/Acep%20A.jpg', teks: 'Pelayanan nya sangat membantu untuk saya yang sedang dalam menjalankan skripsi tahun ini, semoga di beri kelancaran dalam sidang akhir' },
  { inisial: 'RR', nama: 'Rizky R. S.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEptomo58EDrMHfbT3ohVANeLBKG4bQz63O4nikQ3afI7yBw16rHmlnDkC37lzp9NgqqbRmdlwQVQ_jCIGCeRAqJ-070i7BTFxbf5CRoTuUpuvo1hsGflYiTA9h2YM-a0NB3L0CGBb7z9_qlorusnoLH07MMMZT4-YIeZgQiYwxAbnrgfJwNiT1_3/s320/Rizky%20R.jpg', teks: 'Sangat baik, bantuannya sampai dengan pelayanannya kita dibantu untuk paham, sangat membantu, dan tidak mengecewakan sama sekali. Terimakasih untuk jasa nya.' },
  { inisial: 'JY', nama: 'Johanes Y. S.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgPCAXUf0jz0JGoeQqo3_Ey8-5Y-gTvIFe2CjLXQF_d3kAhhk9edP6o2Wt30W1BhXdC8jpQnJUvhM0LzBl2P7oA1XjHcbT6opc33FS9IoTy1DoPg1l_xD_qIydvSj1t24NQvjm4V5XvkDZ5Kv1fC6cL6ezpbSwHD_XSv9f2xQReYcxrbEMEH6bsQiL6/s320/Johanes.jpg', teks: 'Sangat baik dalam penyampaian materi dan sangat dapat dipahami dan semoga bermanfaat untuk kedepannya' },
  { inisial: 'NS', nama: 'Nia S.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxW-5s7W62fQNaaAaF3141fxpZq4MiWoj2Rb2OqnSv-Q8VgAX8DP82VkZzJ0-OX_vdygyKG7VLQ7w4PLR9RZ71u_Wh_Jh1u0U9Guxu5s5nlxBW_YpRpsa4ypl51s3LZA2kg8cdK6Iy9QrP4yINTwLX8m505QMBN26x9kZsycPWE88ryt8yQUXOcBJR/s320/nia.jpg', teks: 'Sangat memuaskan dari pelayanannya sopan dan ramah, serta penjelasannya sangat mudah dipahami, sangat fast respon super baik banget. Pokoknya rekomended banget!' },
  { inisial: 'PS', nama: 'Putri S. N. S.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg05x8M-cN9bDE5WhgG0cxn6XoDKYLZYFboPMmv4YPsarK3pH8OYV--rODIheJ4qIBsOqlCCFKV-1LY6PyGppCyVpqyBUj4cuAxIgBmzYQCXEbtjBPVVwNbUgsRR9NE7Jc5d6-yIEisqWodjVYVpWqpSMMGMEaP_h4YbzyP2oJnF9g6IIq6Uqf-4aZU/s320/putri%20s.jpg', teks: 'Pelayanannya baik dari segi menjelaskan serta mengerjakan olah data yg dibutuhkan sangat sangat baik.' },
  { inisial: 'IN', nama: 'Irfan N.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBZzA-AuoJVOI364kwfAobh6aGW-AKqo_zOJsSt8eAkaEylYTvt7jSACE1FWAZmxZOAXcoxHJhRaFM5ElLzyab0wNj0bn8c_E633w-r9ppNK7rHch2bySjXs8KEWupWfKdLMIxMp0PnmfQf6fu5LrtxHlzU_1j17hMbloWdRPb0VCRunpEUTwyOtWd/s320/Irfan%20N.jpg', teks: 'Sangat menyenangkan dan mudah di mengerti saat memberikan pembelajaran terkait olah data' },
  { inisial: 'NP', nama: 'Nurul P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgcAOr4zEzdcfz-e5Pg0QMaz9KUQ4Y0FQOR4Gn4Qd4NmFH54Q13pdsnYGyoECx69rd1b3cityw6kpGrkO0Sf1nVhrvdz4NOqaaoeL0JRgtZQryk__rtHeh4DUvGNitjhT_gT1Qsg02LvvB-oxVTfkytzuJxIlV1uCvpNkVvOocj2uMosehlPhzoKRSK/s320/Nurul%20P.jpg', teks: 'Sangat membantu, mudah di mengerti pada saat menjelaskan. Pokoknya mantap👍🏻' },
  { inisial: 'DR', nama: 'Dede R.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhuP_IR5GKaqIpbLGH75zKA_cX7EosWKBJZ_p7R_TJxjLLTUSlg33pgNBAelUnYCXQN5dVWHN4_1XEkzjal_TsQNkpCm77uWILXq-dpTQU8WubuU0jEP2C1nscGzMVH-_nYQVx_d7zIp2pRpA7sMxhJ8afLwxTzWfisCG3qkLQX7gyeQU61FLxnFq9B/s320/Dede%20r.jpg', teks: 'Sangat memuaskan dan membantu melancarkan proses skripsi karena di jasa ini dibantu untuk belajar memahami isi dari skripsi dan selalu fast respon' },
  { inisial: 'MA', nama: 'Metha A. P.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg2fZSGvzOUnT_Ug6WWGKNoUbnKWuRfI8TiaI2TzrxLDri0cSkyWXHyIgmHeUYDx7H_y2PxrxWRwghg1A__u0Tt-c-VE-5OrybiGymFeF_OASQmVXRbYV54j2Y2HCr0l1sjW8jmLGO9mm1Nt77nWyz1rkP4xzjpq8ffgIMcc_67gy1ERwdr_NOhBJ1s/s320/Metha.jpg', teks: 'Sangat memuaskan dan membantu melancarkan proses skripsi, dibantu untuk belajar memahami isi dari skripsi dan selalu fast respon ketika di japri' },
  { inisial: 'NW', nama: 'Noviyani W.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgjbGjX_xFrxFdPvF9Ctx-oiUHMKWuLl2H-yrI0I_42-tGa1WEk94s2NCnxSxufbTuAtJ6NZGXKrkNQYzhOJ0Zyf11Ea3DpXW20vSRpWyuQ6BfT8LLfA5afOmYUlt0gNEWbkUp-mz-6MSPb1ZLKloo2xLVJCaSFwIHooKy_RRLlWBP-yHXKnAX05usI/s320/Noviyanti.jpg', teks: 'Memuaskan dalam penjelasannya bolak balik sampe ngerti, kalau mau nanya nanya langsung gercep fast respon. Terimakasih' },
  { inisial: 'AE', nama: 'Alfitri E.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj2_yt06IWf_TQVMH_35r9Kgu49g--ouapHae9TEUrr0RYo46pSu_X8gD80foQ-ZvrBeY8loXcu9OMM7vNFNs-QOwpunOJ71fqkc_V-YTF7A7q8lOpNU-_gzggxsGvxi47X-iZRWZYrM6OU-5hCHYx5SDFpu5Esfw6oGd9HrZvwXWa1wnUxCDzQaz_F/s320/alfitri.jpg', teks: 'Sangat terbantu sekali, yang asalnya tidak paham jadi paham dan cara penjelasannya pun sangat jelas terimakasih 👍' },
  { inisial: 'HK', nama: 'Hendra K.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKBY5LkSEqRhvrc3L1UFFEZXwb9bz6BDY95bjSMjTsMw--gxbPEis7Rp3HyLJsC_SsbmqRXSseACb_S4cV9Z9XAcsxEtUG4KPQAECEJlf1ZrQ2rsv481kDgxWcc9K1vPf2TehgiHgbWRuhg0HEhRp7aMZRyZRwJ4jcBLblgj3-n2WEm5jzma9nHhVE/s320/Hendra.jpg', teks: 'Sangat membantu sekali dan penjelasannya dapat di pahami, mantaplah pokonya' },
  { inisial: 'MA', nama: 'M Amanta P.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgq-7_WJb7G6Xn0SvlyCzQLnsXldxTv4w6lWYmeaz1jjGofQ5yGgfBlD04DBSJP-aPm5_IZnHOfesLoIMqrpj0MnnWvZyJIEJLlZ5-gKecsxbZutUOjUstasJxoaRkuTdCKEm1aXI8IVGq19Jk1Y_TYQQUiS7GQgll4ytMmEfIJD9wg8Qu3kH4qCJWg/s320/m%20amanta.jpg', teks: 'Semua clear, aman ga ada masalah, dibantiin segala proses dari awal sampai selesai dan dibantu hingga paham tentang materi' },
  { inisial: 'MF', nama: 'Mochamad F. H.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXiovRa-cmttJTF45wxkO0vwJhy9hI63WgpmfdFSqv3XYlViezyMoGw4ppRtBNcAKc3l0EZXA2MQQv9E4PsUT0wmsOSZFcO3wD6RaRVk7qwPnDlGcrxTBnvzK8KV4N_8miAeZ9zGEY0epnRzEunA5JqOrErA7Ls0tDIGWuddrY4eSApUAvAy8uRDgT/s320/m%20fazky.jpg', teks: 'Tutornya ramah, penjelasan serta pemaparan materinya mudah dimengerti. Terimakasih semoga terus maju 😇' },
  { inisial: 'SA', nama: 'Suci A. S. M.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiw2fLuU0guBOPS15TyiUc0NzVegS8htLwVdHxJ-k9WJs9MWH3AfLL7hYRFuDUT4G5yYQ93ZPUYS5v9rEX5EHwvjIGVGNx5AwO00cXyXLFOVdu5o9wdPoZZ0NRaE-JXohsFHNUm5Zk1InFmJTPSZrUsm3-E3tfU5BA81LZ97IDBLFGCg0iRVLcC7I8h/s320/suci%20a.jpg', teks: 'Bagus sekali, pelayanannya ramah dan fast respond, baik sekali, good!' },
  { inisial: 'KD', nama: 'Karina D. H.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjwq_svGzAU4dBZXyoCVhKHzEAF0H_ZyjB1fFXNMbLl5-PhMXWegoLU9dIstSSB8N5lddwAaiRaHbJT7mSEWsn-Lav9EZclZfth4ga46XNYqbAP3K-DwXfmuzTBRDqBpBDRvLCzcqI-GbnxkUyBs3-hrvjTiQRtpsNNprnCfNeU7rifTuQ2nbrXX1EU/s320/karina%20d.jpg', teks: 'Pelayanan sangat memuaskan dan penjelasannya sangat baik dapat dipahami dengan detail' },
  { inisial: 'CS', nama: 'Cita S. L.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhzom-wjn7uno0ZOU8R0HGans27wFT3PQz-VPt0_ligE7yGxOgVIAe94ANXF1DqnU8377Q3XrrW362Yf_UwPpC8lyMnY5voX8iPMf79_g1emM2w5AQvJjwf0SkR9ht4287lcE8XhyuWqGoXPWHwSyRZVxZ-4AkMAnwX9KqgEvCYfPM8NikejkbJUHre/s320/cita%20c.jpg', teks: 'Sangat memuaskan sekali. Pengerjaan skripsinya sangat detail, rapih dan tepat tentunya mudah di pahami juga sehingga sangat membantu dalam proses sidang akhir.' },
  { inisial: 'AG', nama: 'Aprian G.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEieBSLD_O9hC5YMm1EVIyD25GfmMOis80Pdf021K-TqiPWh21gp4rX210MYn7wNezgsuNPwadhTp-K5GkazC4-nSjJMvklzKDjWSmWerMbkFiKSAOpRq3Gpp_tNVvKA4gd7W76aaijqOGl6kkuDCDW2sR81nEGf9m789sqMiAJqLGF6F_LC8QSaQnrO/s320/Aprian%20G.jpg', teks: 'Sangat baik dalam menjelaskan, dan mudah dimengerti, pengerjaannya juga cepat' },
  { inisial: 'MR', nama: 'Muhammad R. R. P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjDcFHSLUPbdbeDLiF2WUylMqwYf93_LjbiF3kfNUVFJZPCBFPY25BQfX4FRoG9-ud00HBi7BKArq1wYBjWlMw7pft0HxvHrIroYWzh7BEdMf_oponImaGz1uEpPPWMD4YrLTlzBCFJEvTp7204U5yg8MYOtCPvjs3E2Uug3g-8L91GKK7ea8Fp4ovd/s320/M%20RIDO%20R.jpg', teks: 'sangat membantu dan menjelaskan semua nya dengan baik, di ajari secara detail dan teliti... 👍🏻' },
  { inisial: 'P', nama: 'Pani', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjRQGC7B5YOmlr6zt4JJbLrz9u7SWwSkPbUBgIuXFvjNV2rG8P4tcM4bzT71nMSRhK3zAUTQoj-wFhOi3bXrmLCqqouSiWd6h4lmccFWeIM0tekpi9ldB93vEQCHU-mGaDELwxSoSIfvYJsadBw8bbHMS3sgZLQ-0DNnQhjR9If0SPDsEi1UqO3G6jO/s320/PANI.jpg', teks: 'Terima kasih Amkobar atas bantuannya dalam pengolahan data dari segi pelayanan, harga, hasil dan waktu yang diberikan sangat memuaskan.' },
  { inisial: 'AM', nama: 'Andhika M.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhpbAEMnzpbY12FoellaEPfTyPTxfXgBAL1ghhEK2HO-58vYvTchasBT7twH0Gq9PmO1nqPS13siydTYXh1lqwX_y3Pr7ihz-ZXEHv1nBFD5Z4pKGTqHsSuV2olgM4izNSK_fmBAbWhuIxzo798wNmsJrV1_wu5_dH8srh35Xv72l9bekRiEXd0sk1r/s320/andhika.jpg', teks: 'Sangat baik, penjelasanya mudah di pahami, sangat membantu, dan tidak mengecewakan sama sekali.' },
  { inisial: 'DS', nama: 'Daniel S. F.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgGMhNl14hkl2Ix6wo8TqZWVENjYxgYvGLh--vDuMZVRV8JwVAByRFP1W4i4_AZxJdwTlO1T5Ng1OcETJSy77_kndfkWACtghAegQmPmEicqDjxjO3R71D71Ks9EeftuM-_zJ9tbBMTXqXWCUtcjVjPqiFzHteLebms77FhiZ6Hx943rzWQEbH8uLFA/s320/daniel%20s.jpg', teks: 'Sangat baik dalam menjelaskan, dan mudah dimengerti, pengerjaannya juga cepat' },
  { inisial: 'RY', nama: 'Reyhand Y. H.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjt0e1JmDeLi_owBZ90KujHvv73w01r4zP9YAJF4KBGy8Vr1KOKVX7lWNzXnydPEi-m0E4pPz4cJyV6qbtnOgnaqdduZ5US_LifGnZ596DDEZ9MU7Ubr_N6mZp3ySuuZmgMhuwhrjXOnJHK3G2evNwiz_6fwhX-E1_Xxg0Y3QBqY3FjMR4amlX-OukL/s320/reyhan.jpg', teks: 'Sangat membantu dalam pengerjaan bisa revisi dan dibantu hingga selesai' },
  { inisial: 'MA', nama: 'Muhammad A. P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEid0kEb1-J8Hsbht69F7wHiK0zv0rvX9t-81G1tk7WpXUWODe2XpGssp0ReFXDdLcM0WsnB0eeUj8qjO2TyKeumT1Uy_bfCAIyIoYPU1jr5fIETF76A8ChdF5a1oQSfgrh-N40pp-Y00HEbih9d8wPoMciS74Q_Yz--5rmvJZH-1D1qdfxrxzYglPyT/s320/m%20anugrah.jpg', teks: 'Sangat membantu dan memberikan penjelasan dengan baik, mantap terimakasih kang' },
  { inisial: 'R', nama: 'Robas', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgYF9fmhxeO7a374gYBcPV7LYum4KpIY5LBs6Rv1NyL7rcQ92qf1yq8f1YUFSdmmCM2Agfn81mg3gl3FrPFAvpkYXbws5q5jv3dB9jUxOOVXfFHV_dfasFc_tCLJE4YrCzFd02RTMz3gcEMxMsOpdsYDAuwBzdIeWCwb9toXuuk0xitn__2f-qHrSqI/s320/robas.jpg', teks: 'Sangat membantu dan mantap, cepat direspon, mudah dipahami, dan mudah dipelajari' },
  { inisial: 'AG', nama: 'Agung M. G.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjWYjjomVv9xt3Agb-xQLftlsSR6LfukGEium0O49gq_CJSedIOP3GEvqOrr2UTBCAaB6-zSpDnwaIsXrl3z0ybIbZrlcsx_NvIcfh_MjIemes24aC6RMSjs7rnAXrUYibPWEdEdPsmqD2ybjvuOAVBbe_PUvkVwUSrTn6bXhPD8eUToPHA25-L37U7/s320/agung%20maulana.jpg', teks: 'yang saya highlight paling pertama yaitu keterbukaannya dan rasa care buat mahasiswa sangat baik.. saya merasa sangat tertolong oleh jasa ini. thanks a lot!!!' },
  { inisial: 'YA', nama: 'Yogi A. S.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjLa_qwX9CSYWsXi5sRYv62MkuLFD3AEJgR8fOFWlUZhrfaC_ktzF2JBLIawCOvcVjx6smnMOTZs5-EQWfTnX9aX-rL2dPLOnc5q_1891qT47imUxyOzbMpsK-LGcWoHdZRffDh6-YfJnaWkxcrEpliw1qKB8ppNEfqJna9SQWkQxWd7pUnjw7aHCJD/s320/yogi%20al.jpg', teks: 'Sangatttt baik dan ramah sangat mudah dimengerti dan sabar dalam mengajar' },
  { inisial: 'A', nama: 'Anastasya', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEicLMW4GgHG5rHXYBIKKA4tCzO5HWRsRigDuIt9456rzwS3weG4KHamm7FO6NYbc1QIPoH3yZ-a8NnZ6cNEmZrKPA4ktlk0qJpQMkD83eVHnhhyA9nnra4R5IJC2fTynkq3Gns_9A7e6FtL10scNLJ9qtu3P22yehTSv5z2uiGo3sgX8ckmgS0OIUJQ/s320/anatasya.jpg', teks: 'Pokonya the best bgt, cara penjelasan, pembelajaran nya dapat di pahami dengan jelas, selalu on time, fast respon, pengerjaan cepat, mntp pokonyaaa' },
  { inisial: 'BB', nama: 'Bella B.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEivRydjFiKeYUBGe49106C67lG122l-Z_A8K4dnm4IWE9YeJNg6yVRjfOzktFN6nlcYfki0nnz7kuQxKVVcgn3gqtqI3NNx99NTPeUejmj7EkGitLxX-qniH9tpX0DvgNF_p2PHn9_Dfo5ovZdhHn00lbYaXXVDZF6V7gpauYZpDplZwQV-Z6Tu5fEQ/s320/bela%20b.jpg', teks: 'Pelayanan nya sangat baik dan ramah, terutama saat menjawab pertanyaan sangat fast respon' },
  { inisial: 'FP', nama: 'Ferdi P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh65bnkZQSp6sUvMna5saM80sancvdAawcWZbLjLMQvEpt0cwK9Z0gEP_921SpTqdMzpQlim-XAlRcZLPHSmxIYc_6E0O29LvnRVdgvslkBiV-j95cxcuFwOi71sORXxV51gbijJg_lvGjGXZCc5tpktqLheSS8KB669NMyzsAV8MeZP0dgo4ZKbC7l/s320/ferdi%20f.jpg', teks: 'Penjelasannya sudah jelas dan sangat membantu, pelayanannya pun sudah baik, pokoknya mah sudah mantap semua lah 👍' },
  { inisial: 'TA', nama: 'Thomas A.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiUMzQb6jIIOHphSZrfxGRK2HlGrty9lSmPJPaSOhWp0Sxw-QIa-DA34kTN7l6yAve2atCjAG43L-SZ3LVPsozNTtW6nTteSVAN9ECPPCbJR4Xb_38oqy5npVydkUEVYCBXlR-b4KUvLeib8GUWoyeBU0GABayfgo4iXBrsDQP8UoOXLDxs24JkVpSD/s320/thomas%20s.jpg', teks: 'penjelasan yang diberikan oleh akang nya sudah cukup jelas menurut saya, sangat membantu dalam pengerjaan' },
  { inisial: 'PD', nama: 'Putri D.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiNhuKaWarL8tQIUMGLvz60KdtYo6tqDa_5TACUwom7UngmqtUWYGTZuYshbZm-M_Acu_vbA9yyslH64jMgUZssozB18miisxGdtwHGVNuK7axvZ1nEDqY5iQ3SO3TQRWUQucoX5Srd6SEgRLqfLo7EkRVsqQmQsYtSzqZF_Q0DbhGnHYJPxzZOw0Jq/s320/putri%20d.jpg', teks: 'good, mudah dipahami penjelasannya, mentor juga sangat sabar saat saya bertanya dan fast respon' },
  { inisial: 'MH', nama: 'Muhammad H.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj2EdGC7rUTh2RSRu5QZTB3E3kaARZ6xhz-U7jZq5_rq804EJR946Ig0rrsE4bUGlrEVgX40g23PwUD9BVY1yqGMq9dJ0aHvx3l76vXkxUT_gXZ_ap1Xi1k14W5XgFBrkzDykIY4BI3qTKViI5MeY889dUTjFORLABBSVoakXlPyLIdcF-C81DeWgVo/s320/m%20hidayat.jpg', teks: 'alhamdulillah, sangat puas dengan pelayanan dan penjelasan yang di berikan' },
  { inisial: 'MI', nama: 'Muhamad I. N.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgsMNdSTPPvdCp1jAOG_PXVgsfDaZMkXwo0ZJnJkqu2LEX8t_kvrQ9hSe0lP-FHGXg_0WV8MBKa4_YPlSxESu9FaN1yuPT7eH53VXHoVz5c8vS2o3yGyYPa_WXssAVSiTQ0Aor5u45-RIsq5EVzRr7HOgQZllG3qMM8wAV_7CbzW5n-Ppkf28XkxHqC/s320/m%20ihsan.jpg', teks: 'Baik, penjelasan nya sangat membantu akang nya juga lumayan fast respon' },
  { inisial: 'AD', nama: 'Arif D. Y.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEihC0k6OMOgjjK44dLRW0CbkVaLWHKYZc80E8MV126g0A85Sa7H3DVY5Dnj9BnFoegBDE-72qyocHGVsTvNRcZgCg_z163naqO_im-9FqTJZtzFzmMdT0k76wxvvVnn2apjNTu2sRs4anUm3tApcMiDPf0TShGKROtEVuiiO2yHYa6JSQLjq12ho97J/s320/arif%20d.jpg', teks: 'Pada saat pembelajaran bab 4 dan 5 sangat mudah dimengerti dan jelas' },
  { inisial: 'LA', nama: 'Lulu A.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjWZukeSN7FRTxfQ-bmk87Hy2DoBnXNQn3u_BaXWbg2zOOyt5VPIYZAZhqs-AYsCfgIEw8Qt57gjgqx_NOLv_HvkU8CyDelmzch_Ye-ru3N5doZHOmb3TD64EvdOLcHYYZ8ihPFffz9g7Rjmj5IuZ4UJArkwSBBmK5UwnDL1wlb3ActyoJeb4GOT/s320/lulu%20a.jpg', teks: 'Ngajarinnya sampe detail bgt, sampe akar akarnya. Sabar banget menghadapi org lemot sepertiku🥲 trusted banget pokoknya!' },
  { inisial: 'AF', nama: 'Achmad F.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxRmIaU_InhV-meNO6CZSmd9v2j1wrLlHEUKYufapfMRiP-Hk155TOyPpzbhNv2MC_4P85jz6oD_B2LATW7LO1arkaLFtGHuvvLl_WDbVxtdXqwEvl5SxMlQEkLEE4QjIRLKqIE89DyMGfA-RGoiWXipP3uTesYuvqstId6H7ZAQil1uqVGl3rD1Ay/s320/achamt%20f.jpg', teks: 'Bagus dan membantu yang sesuai harapan, pelayanan bagus dan bisa dimengerti' },
  { inisial: 'YE', nama: 'Yosafat E. D.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHxBSg2gTzzv94tXe32bFjJG4mebtGTIWVT050LAzfsTX_dH2f4DefDTIjeaZx9mVcEdogPzRBGDe5G42gCEAgbEfArXc-EbXQ5OJ7xk5AkDqQuyJNSd_pZeTT7XHoPdFvxVOBm98_coj6-LMMmqrwfA1esXeUKAdUeTB_-HqeDFdqyJ17FQXDqj2H/s320/yosafat.jpg', teks: 'pelayanan sangat cepat dan fast respon pengerjaan juga cepat dan hasil nya juga sangat memuaskan' },
  { inisial: 'F', nama: 'Fana', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgOVkKCyuRMaao-E638GW_zauYNb9lf9cPlfXPW7WR57Aoj7ADYbsYn9qebfmKZ406gGEfYmMTLKkhCDbbSRcUdbp4PaiGzX5EX2JomYAy9CR9Vqkei86R0l3-QpttWUXS38Bclig9oZ0JRM-xXuXfS9MgOdpptOA1i2vON87SHzetf5G8S5h-MRyrl/s320/fana.jpg', teks: 'Baik banget si aa nya, di chat tengah malampun buat nanya-nanya masih fast respon. penjelasannya juga mudah dipahami, dan yang terpenting hasil olah datanya rapi.' },
  { inisial: 'MG', nama: 'Muhammad G. N.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhn3j8zxfHUsL12uVsLRIGbmTWxJtShd8zwZDrx63irQ9YOUKYxUGzOPO9d-p3pSlxHgp_iFGfHQSgq-eEjy6pf_fadAPeIB0ojjm_B7Q6sBG62OJa_BF90avH2ybr4gRSFyx37P-UT7rgVdvgUJLv-E-hWopLLd2nn1x3qRSySo7pJwQNaHlbRzCU4/s320/m%20gian.jpg', teks: 'Sangat bagus, ramah dari segi pelayanan, sukses terus buat AMKOBAR' },
  { inisial: 'MT', nama: 'Mario T. P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgjKWmPNsrP6K0kVIBjz_id2aPe2WtmzvsG2BISh_-RJGDOd-Pw8u7BTAZk2o5Smw78pJ0nMIDS63AdSTMDi8oTQqEbsgIxOY5jipLKh8GDDy2jDD_EfgUnm724fcvB7ZN2IY5Sov7IA5WT36DJ_9ieX3k5C4nYZIfyxv9dSwLzbTTBsOfhNl5bTX5F/s320/mario%20t.jpg', teks: 'fast repons dan mudah dipahami dengan jelas sukses terus kang' },
  { inisial: 'A', nama: 'Andiananto', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiulx1r-5_cQeDuPDackb3WH1TViAzTXJTK3OAwy8Atj5z43duENio7ONytzvkogyeVf39Yi8Qt57gjgqx_NOLv_HvkU8CyDelmzch_Ye-ru3N5doZHOmb3TD64EvdOLcHYYZ8ihPFffz9g7Rjmj5IuZ4UJArkwSBBmK5UwnDL1wlb3ActyoJeb4GOT/s320/andia.jpg', teks: 'Penjelasan sangat mudah dimengerti, fast respon dan juga profesional mntp🤙🏻' },
  { inisial: 'LP', nama: 'Luky P.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhEJT6-ueOz7hmnQjwd_5OeXXK2YuyyOf9R59B99tjJjBtcGv2uJclINOlG4wNmS9ISBQIIIyHDNJhGb9NB_Zc-pfAKZrkAQ6wlCnrCLuU8l_2mtvtFlrGcActQQI/s320/luky%20p.jpg', teks: 'sangat membantu dalam menyelesaikan tugas, bagus, tepat waktu dalam pemberian tugas.' },
  { inisial: 'D', nama: 'Dwiky', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhvAJqXFzL0xVosOM5gCjoFP5r0OQlfvOC0TJZVR2RDZC1NDOP6dMxl2psSM_L9CT3Od3yjVcQ1_GU3GgUYW03kbRgpTOV00KPLS463AdM_VRPtfJBWO2bR61Yll3b_ldxl_4Fawu193mGEbwAFzxWcEySBIQLLuPONwOhi3EhRF3dwl3cp9gDxBB0q/s320/dwyki.jpg', teks: 'penjelasan pembawaan materi mudah di mengerti. Pelayanan mantap. Belajar berkali kali bisaa sampe paham.. sukses terus buat amkobar' },
  { inisial: 'B', nama: 'Baldan', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiR88kErbKtV-cIc9jdeTuISXr-ucXITtk-ZzHhxGJYe6R9sruGgh4fpT9MBZpDFOlp0oxVyNGBejq_VIu8KESZ2gVmtxe80RnVtDlcb0piqSh6yDnlLNek_y9SKPiFmBm8nRSqsw2Db6Wp7JeR2KEXrpOvCMjIh69xONx0JY5HFaqKxFMXqAIesD8o/s320/baldan.jpg', teks: 'Sangat sangat memuaskan. Penjelasan nya mudah dimengerti dan juga proses pengerjaan nya cepat. Terimakasih banyak kang andi. Sukses selalu buat amkobar' },
  { inisial: 'EM', nama: 'Eka M.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9YI_O9BwHPjl9y2j4KwOkfqB1uKDgWC18etp7y2RcQAXVSlvIukaXLYYFzotGVBK7OQm6Sxkt4bwET1MEpeyARmRXOkLtPme5cGQLBAnOii8030Tp85ol8rHPHsL8qjcZGUdH_XM9MhYYc3o5lYVoMe3OQ5EXDU6hrjL9DgnC3JndvC6K1Yjmp4pB/s320/eka%20m.jpg', teks: 'Fast respon dan penjelasan mudah dipahami👍' },
  { inisial: 'MR', nama: 'Muhammad R.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgR32d2QErBZPxTExiAjXdnEmntZkvYLDlsKT93tjD_RLnrm-IvkKGer5gObwCT50wxibwmItx0yFh8jMqcj6hYq5YAwuLYj4rFOSlyy2QAcIiI17TuMW6aU1i8lj3edjaSZLEzftWCDs-8Kjrqx8ndY8rDbcp982wbHGF3zLCn5qmReH7kSkkUKe7s/s320/m%20rizky.jpg', teks: 'Pelayanan sangat baik dan penjelasan dapat dipahami dengan cepat. Terimakasih🙏🏻 Sukses dan sehat selalu👍' },
  { inisial: 'VL', nama: 'Vivi L.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_hiXwW3hGH4-f9-Di7QNOfd104E1TiHoIk-LbbfRBzmaIs-YORS742lZq9WOmzGwVBW2hXP5-HYANuhCXzxJnm6iFPFSnrZLVX5U6GTNj01ZE4WCtQo9Lm9B7YlEpX0BI_uM0gR3z3uCNoLAS7XGCg-7MojjHoLhzy-ecZXzyo7KNIA_MW7UlcB1b/s320/vivi.jpg', teks: 'sudah sangat baik dan sangat dapat dipahami saat pembelajaran, sangat sabar dalam menjawab pertanyaan.' },
  { inisial: 'RF', nama: 'Rifky F.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg7XMugnffVvMwbBc_ESU2bW2_2lCpZHwr9LPcQ5HQMU0bkDryTxbWcab5NTKJpsB02kUCyswRaia3GJ-c2IYPQ9OIF4IcTTcUYN4Qt_ZIdtsHEDMMqOWAxD0MeqvOQtJHcFRHoIc8ASNgSAv9jwUkIVsR64OiUSZAQvnxtOzQt1UK6ImUGD3iSjKP8/s320/rifky%20f.jpg', teks: 'Alhamdulillah, semua penjelasannya sangat mudah dipahami' },
  { inisial: 'AI', nama: 'Aishyfah I. A.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhR_HsaAr1H1kn_3-oylzUBXCr3uDNgofqQD6cbocHvrOvVIfVlEqbEKJO4denxgaRKbM_u8FPXueP4cJ0ZcQsilzNB0Qj8SVe_e9Mqaqcwm4oycULU-NuDbqZIulUIbY6wtVhc4FomtJDRrs-8Aszq1hQZMnqmk6W0wymAtnHkijcpT3yt0O6c0etc/s320/aisyafah.jpg', teks: 'Dari awal nanya-nanya soal biaya sampe waktu pengerjaan sangat ramah, saat pembelajaran dimulai menjelaskan dengan rinci dan dapat dipahami. Terimakasih banyak ya kang' },
  { inisial: 'HK', nama: 'Hilsa K. S.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEihQKG81OLgFf9EpVoSAZPE2zu_yYzWFDMmzzI2-WEwCzI_QtFJDRb9RfhEWZ2Qy5J5zW7gZfQKR80FWV4joNrNSXh8Xk0piU4KsWe77jMlY376_rovtpHdVhmGLZMJ8MRDI4xWIIbjWqeXvlNkczJUrV9epgB4myrvw8ZKtBsLruOvnLMVPVQnAvh_/s320/hilsa%20k.jpg', teks: 'Dari awal nanya tentang berapa lama pengerjaannya sangat ramah, saat pembelajaran dijelaskan dengan detail dan mudah dimengerti serta waktu pembelajaran sangat fleksibel.' },
  { inisial: 'DR', nama: 'Dani R.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh5E6q7cLw-ELY4Ues5-DJncSgrYYgxt36TjupGXBV8ctoOsJ85x-4i8nl31CF9XgQwH_OZw46C92ng0vy3U7MkWNkusvoPuAjnQ93hC5a9asNaH4fMDp3cExEZ1pwPTjU2nIwGZgXRdd9IHzEXfV1EAwamMyDPnahL_I7Yv2D6pD1AYFYh7TVyr1_1/s320/dani.jpg', teks: 'Sangat Baik dalam pelayanan dan penjelasannya' },
  { inisial: 'TA', nama: 'Tia A.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhvBHZPtg6kzeczsHVnjtuFinXGSrtB8MLq4p_gSa9NzgJOyf5tqV8ZbS71I_X47yE3RJhX2UjhWY93i3w5sUu0lFVMZXEK_x2EwpOhP4s3Ra4y7han_mUQZMb666gZCCf5PghKHVk_k_8eu-r7EGq3pGKPL1-HJgNw4GtOTlbPd1dD3XwnG--ib_oi/s320/tia%20a.jpg', teks: 'Penjeasan sudah sangat dimengerti dijellaskan sampai paham, baik banget pokonya, sukses terus ya' },
  { inisial: 'AK', nama: 'Ade K.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjX88gG7eq1TFkBb2Vvi7Hlp9Mfm7xkGHcy3yuUzE_-bWWtbZTu9R9gNuL1OlFW-FZ7Kskn4bf08T9nKPan25O8cUzXkLXGifPACGhfUkgTfT1e52s3UzVFQ6f_nHPbim2aQ1o4a2SxykuB56l3KHitwa8_0JuQhA_t1fNIkcp-BFPI8LNQdZ10LMlw/s320/ade%20k.jpg', teks: 'Sangat membantu sekali dalam mengerjakan olah data, proses pengerjaan sangat cepat dan selalu diberi penjelasan setelah hasil olah data selesai. Rekomended!' },
  { inisial: 'GH', nama: 'Gina H.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhmWlUOQjYGSY8osYuYbzrOQwF5p4Yt-HNpyeM4_h9b-Unt8g6faENAJICCHjtcgKS8qQYeDAq1B_xrfyVSRC-CmmwtGiukOCkhbhROofK0yq-EYNbZ92pijT9uODjqTVr6DuZneIhDZqs9zOcDMZC3cbEX1RpJzPA6rIjyACwiFYp-KbSS4LGR-E5W/s320/gina%20h.jpg', teks: 'Sangat cepat dan membantu banget dalam mengerjakan skripsi' },
  { inisial: 'FD', nama: 'Farid D. A.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh3LKg4AYVZw8jix3shyJK2TEzqoxh8aFl7mh8GDtF9TDcurWlEyXkK70P_XlCYcKCOl29JpnlsgR7EfqhtAKEG45VL0sipOzvtgWXkUzdNaVp4aSB3GUFcj71Cla1pFS_gSMQeBR4Bu72-hXd9ZXw4uf8XJXJNKNZjkkBPqGOdXh_3hSQ_a2r0x256/s320/farit%20d.jpg', teks: 'Dari pelayanannya sangat sopan dan ramah, dari penjelasannya sangat mudah dipahami dalam menjelaskan hasil olahdata, sangat fast respon 🙏🏻' },
  { inisial: 'RA', nama: 'Ratna A. S.', subtitle: 'BAB IV–V', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjCehFuHjW2YTGOzktsx9EmLhr6wd5PQijREGwvg0ffzk4wOK9SxK7gAMRUrdndp11oQR2nYtqSj6ZVdJaGrC4RQCl-Jf4abPzcTk0rgXderxAbU5EuEXdWLxjJBA6WkXbh5sSBSuNICE8UXzj-nUoBT0iFIhQGuTpmWt1Va56hmOcnyaM4mn4c2OLj/s320/ratna.jpg', teks: 'super baik bangeet selalu mau direpotin kalo minta bantuan, cara ngajarinnya juga jelas, sabar jawab pertanyaan yang mungkin itu-itu lagi, makasihhhhh banyaak 🙏' },
  { inisial: 'TM', nama: 'Tresya M.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEge2xOptQckNnogbLQ871DBEbtC23oBxAym0fmMLwKOZqa7qvpjob1jOgbfrRcLDRoMzmtnkpFn30SspKKtlKXpcY3joxGePa_BnIY6KoGLzr5sq7NxcZBKP8fNV9ltZEAoLnqD9Qb70LX-bLIIN4iFmX0kfC_MhBRkAixroSm3Qiv13QlQlK7caDku/s320/tresya.jpg', teks: 'Sangat Sabar dalam menjelaskan, sangat puas dengan pelayanannya' },
  { inisial: 'BD', nama: 'Beno D.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhkH9sSIRabHEwsxsQBsetkAhbrF_7cHeQCSKKxHGRUSbz02JpgfdsUVmbEXby0B2IRDPFI2Wb0uW7ZkFxRe7W_Rijhtqml-hkkmWb8xCIt9bNpn0JHWcFkrKXHMr1H-EYCM_hoLQKJEclq2Jr71ygD7NRJYeEdeTzFqehxuWafYdiypdG3m6PPZfno/s320/beno.jpg', teks: 'Sangat Baik, Mantap dan Jelas pada saat menerangkan hasil pengelolahan datanya' },
  { inisial: 'MM', nama: 'Muhtar M. K.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjk90CiM5L4OfM9Yvqaze-U03NwIOibV7pylJM5kk-kiB3kUP1a_knnh_X7hGXU1XeBmfy-pnXqtIvkUJnxmEGc2i-OmzUQSeYkDgaoaVfPWyYcgZBMZd_N6MwibZ9biO3JS6lMy32GyP_PwuQEiDm-9xQfVKyDbWohcVeF6YGozbir75dRrN-IhNrj/s320/muhtar.jpg', teks: 'Sangat rinci dan memudahkan kita untuk mengerti' },
  { inisial: 'AA', nama: 'Anggi A.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjZttjvTu1Xaw-trt96GF9uv-XdSVMejffwKKr2m6cNTE-f69XI2ZfK1Dx1X5fGQzOuvBc-imZ7dY37v2xv0qywLwZIncRVmEPCaCOdpb1H0OWauxmmdgTpqp3LkFLpeFLGr-OzF912jX4aZUTJ8_7N6a0z06yyIqW9JQK1_QQLp1sX9HWiqVANA74B/s320/anggi%20a.jpg', teks: 'cukup baik dan cukup bisa di mengerti dalam menjelaskan' },
  { inisial: 'AM', nama: 'Argi M. G.', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgo0ty5QFEQkCn0aITO9WEybewlylfJ_FottW4OqgkV2kEmVbc3h83FKRfAs2xvSpMRFqis6F2erAUYRCO-jX-FnKFEq2O6skYasi9q-EBAyxyR6sWF1Zsi68d63-2r8vjYJ_MBkNS2RVtHXEgakWI7NSF_w5j_Wo_u2lBwYZGDHKjPMuP7WwAsay8S/s320/argi%20m.jpg', teks: 'Sangat membantu dalam menjelaskan dan sangat puas' },
  { inisial: 'RA', nama: 'Reza A.', subtitle: 'D0', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEildzLtt2nvvVquPG3RjtEA3BV6ARubVmnkCXAQUuMJW1cZ2zv8Qfgvw8c-K9uu8fpGmcqObalC9XFXVv80TY35LNS-x4bQYkWSRpPKlSFmWw0AslDYGvjnjQdC3gikE8XEhOfcMcEy7Ukaqr3DS1w2r_YL8P1CNA1FO-Bw4lz_5EmNvYpmc8ZLPLC3/s320/reza%20a.jpg', teks: 'Mudah dipahami dalam menjelaskan hasil olahdata dan sangat puas' },
  { inisial: 'MY', nama: 'M. Yusuf', subtitle: 'BAB IV', rating: 5, foto: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjud4cG4appWg6KhleRWTfOpFdMfdRI4ZEt2e0QKJjedfFONtga4xmPebLJJMgEJuHkhG9AQlelLEBkNFYm94oEyNxBJBGXyMJqVog90NVsmDEqJ00CoSouLUS-ts6RTIO8aRwvOGJIaLwvZuNr8zpHP79FmGyrS3Wfvi_HWZZJKGZuZmMYZRs33SND/s320/m%20yusuf.jpg', teks: 'Hasil sangat baik dan puas atas hasil olahdatanya' },
  { inisial: 'SA', nama: 'Shayna A.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Pelayanannya baik dan keren banget, bisa chat kapan aja dan responnya juga cepet. Hasilnya juga sesuai sama apa yang diminta, cara jelasinnya juga gampang buat dimengerti, sangat amat merekomendasikan!' },
  { inisial: 'IH', nama: 'Ikhsan H.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Pelayanan ramah poll, hasil kerja sangat sesuai. Recommended buat teman yang tidak hanya sekedar joki, tetapi juga ingin paham dan ingin bisa, karena ada garansi revisi yang sangat dibutuhkan.' },
  { inisial: 'A', nama: 'Adhi', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Mantapps bertanggung jawab, fleksibel sangat membantu dan membimbing buat kita yang sangat awam sama penelitian skripsi semoga bisa selalu bertumbuh dan berkembang!' },
  { inisial: 'H', nama: 'Hadriyan', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Sumpah guyss aku rekomendasiin banget ini, bener bener worth it, pembelajarannya juga masuk ke otak, diajarin sampe bener bener bisa yaa' },
  { inisial: 'RI', nama: 'R. Ibrahim', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Terbaik pokoknya gabisa berkata kata, hasilnya memuaskan sekali dan mudah dipahami saat sesi belajarnya' },
  { inisial: 'D', nama: 'Dhia', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Terimakasih sangat senang dan di bimbing juga membantu, doakan saya semoga lancar sidang akhir amiin' },
  { inisial: 'RP', nama: 'Radira P. D.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'terbaik semua nya fastrespon kerjaan nya rapih semua nya baik dan tidak ada yg salah semoga kedepan nya lancar dan terkenal' },
  { inisial: 'R', nama: 'Rianto', subtitle: 'BAB IV–V', rating: 5, foto: null, teks: 'Pelayanan nya ramah, respon chatnya cepet, hasilnya sesuai dengan apa yang kita inginkan, bebas revisi sampai acc dospem dan yang terpenting pembelajaran nya mudah di pahami' },
  { inisial: 'LN', nama: 'Laiqa N. N.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'okeee semuanya okeee baikk mantaap pokonya, ada yg gangerti tinggal tanya dan dijelasinnyaa jelas bangett, pokonyaa joki disini recomended okee pisaann' },
  { inisial: 'A', nama: 'Alviyah', subtitle: 'BAB IV–V', rating: 5, foto: null, teks: 'Saya sangat puas dengan pelayanan joki ini. Prosesnya cepat, hasil sesuai permintaan, komunikasinya sangat jelas serta ramah. Pengerjaan dilakukan tepat waktu, bahkan sebelum deadline.' },
  { inisial: 'G', nama: 'Gandi', subtitle: 'BAB I–V', rating: 5, foto: null, teks: 'Pengerjaan sangat rapih, menguasai sistematika penulisan bahkan sampai ke penyesuaian sesuai keinginan dosen. penyelesaian masalah cepat dan sangat tepat.' },
  { inisial: 'L', nama: 'Luthfia', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Belajarnya enakk bgtt bener bener detail mudah dimengerti, makasih ya' },
  { inisial: 'GA', nama: 'Gia W. A.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Cukup Baik, tingkatkan joki nya. Kurangi netralnya. Mantepppp kang' },
  { inisial: 'IF', nama: 'Idham F.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Secara keseluruhan sangat detail, penyampaian materi saat belajar pun mudah dipahami' },
  { inisial: 'SR', nama: 'Salsha R.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Hasil sesuai dengan sistematika dan pembelajaran mudah dipahami, serta jika ada yang tidak dipahami, dijawabnya sangat cepat' },
  { inisial: 'IN', nama: 'Indah N. A.', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'hasilnya baik, cara penjelasannya juga bagus, langsung meresap kedalam otak. pokoknya keren' },
  { inisial: 'E', nama: 'Elsha', subtitle: 'BAB IV', rating: 5, foto: null, teks: 'Baik, penjelasannya detail, diajarkan perhitungan spss step by step sehingga mudah dipahami, diajarkan sampai mengerti. Kakanya friendly sekali jadi tidak canggung. Trusted banget pokoknya!' },
];

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const NOTION_TOKEN = process.env.NOTION_TOKEN;
  const NOTION_DB_ID = process.env.NOTION_DB_ID;

  // Ambil testimoni baru dari Notion (jika ada)
  let testimoniNotion = [];
  if (NOTION_TOKEN && NOTION_DB_ID) {
    try {
      const response = await fetch(`https://api.notion.com/v1/databases/${NOTION_DB_ID}/query`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${NOTION_TOKEN}`,
          'Notion-Version': '2022-06-28',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          filter: {
            property: 'Testimoni_Selesai',
            checkbox: { equals: true }
          },
          page_size: 100
        })
      });
      const data = await response.json();

      if (response.ok && data.results) {
        const getText = p => {
          if (!p) return null;
          if (p.type === 'title') return p.title?.[0]?.plain_text || null;
          if (p.type === 'rich_text') return p.rich_text?.[0]?.plain_text || null;
          return null;
        };
        const getSelect = p => p?.select?.name || null;
        const getNumber = p => p?.number != null ? p.number : null;
        const mapLayanan = jenis => {
          if (!jenis) return null;
          if (jenis.includes('FULL') || jenis.includes('Full')) return 'Full BAB';
          if (jenis.includes('IV') && jenis.includes('V')) return 'BAB IV\u2013V';
          if (jenis.includes('IV')) return 'BAB IV';
          if (jenis.toLowerCase().includes('olahdata')) return 'Olah Data';
          return jenis;
        };

        testimoniNotion = (data.results || []).map(p => {
          const props = p.properties;
          const nama = getText(props['Nama Client']) || '';
          const inisial = nama.split(' ').slice(0, 2).map(w => w.charAt(0).toUpperCase()).join('');
          const parts = nama.split(' ');
          const namaShort = parts.length <= 1 ? parts[0] : parts[0] + ' ' + parts.slice(1).map(w => w.charAt(0).toUpperCase() + '.').join(' ');
          const jenis = mapLayanan(getSelect(props['Jenis Layanan']));
          const aplikasi = getSelect(props['Aplikasi']);
          const subtitle = [jenis, aplikasi].filter(Boolean).join(' \u00b7 ');
          return {
            inisial,
            nama: namaShort,
            subtitle,
            rating: getNumber(props['Rating']) || 5,
            teks: getText(props['Testimoni_Teks']) || ''
          };
        }).filter(t => t.teks);
      }
    } catch (err) {
      // Notion gagal, lanjut dengan data lama saja
      console.error('Notion error:', err.message);
    }
  }

  // Gabungkan: testimoni Notion (terbaru) di depan, lama di belakang
  const semua = [...testimoniNotion, ...TESTIMONI_LAMA];

  return res.status(200).json(semua);
}
